// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `FindOwner`. */
export interface IFindOwnerResult {
    id: string;
}

/** Result of query `ListInvitationGuests`. */
export interface IListInvitationGuestsResult {
    id: string;
    public_id: string;
    owner_id: string;
    token: string;
    name: string;
    group_name: string;
    face_scan_required: number;
    max_guests: number;
    status: string;
    active: number;
    created_at: string;
    companions: string;
    references_json: string;
}

/** Result of query `InvitationGuestById`. */
export interface IInvitationGuestByIdResult {
    id: string;
    public_id: string;
    owner_id: string;
    token: string;
    name: string;
    group_name: string;
    face_scan_required: number;
    max_guests: number;
    status: string;
    active: number;
    created_at: string;
    companions: string;
    references_json: string;
}

/** Result of query `InvitationGuestByToken`. */
export interface IInvitationGuestByTokenResult {
    id: string;
    public_id: string;
    owner_id: string;
    token: string;
    name: string;
    group_name: string;
    face_scan_required: number;
    max_guests: number;
    status: string;
    active: number;
    created_at: string;
    companions: string;
    references_json: string;
}

/** Result of query `CreateInvitationGuest`. */
export interface ICreateInvitationGuestResult {
}

/** Result of query `RevokeChangedInvitationMode`. */
export interface IRevokeChangedInvitationModeResult {
}

/** Result of query `UpdateInvitationGuest`. */
export interface IUpdateInvitationGuestResult {
    id: string;
}

/** Result of query `InvitationStats`. */
export interface IInvitationStatsResult {
    invited: number;
    accepted: number;
    declined: number;
    pending: number;
    companions: number;
}

/** Result of query `InvitationGroups`. */
export interface IInvitationGroupsResult {
    group_name: string;
}

/** Result of query `SetInvitationAccess`. */
export interface ISetInvitationAccessResult {
}

/** Result of query `RevokeInvitationAccessSessions`. */
export interface IRevokeInvitationAccessSessionsResult {
}

/** Result of query `RotateInvitationLink`. */
export interface IRotateInvitationLinkResult {
}

/** Result of query `RevokeRotatedInvitationSessions`. */
export interface IRevokeRotatedInvitationSessionsResult {
}

/** Result of query `RevokeInvitationSessions`. */
export interface IRevokeInvitationSessionsResult {
}

/** Result of query `AddInvitationReference`. */
export interface IAddInvitationReferenceResult {
    id: string;
}

/** Result of query `InvitationReferenceObservations`. */
export interface IInvitationReferenceObservationsResult {
    id: string;
    observation: string;
}

/** Result of query `InvitationReferenceImage`. */
export interface IInvitationReferenceImageResult {
    image: Uint8Array;
    media_type: string;
}

/** Result of query `RemoveInvitationReference`. */
export interface IRemoveInvitationReferenceResult {
    id: string;
}

/** Result of query `CreateInvitationSession`. */
export interface ICreateInvitationSessionResult {
    token_hash: string | null;
}

/** Result of query `FindInvitationSession`. */
export interface IFindInvitationSessionResult {
    token_hash: string;
}

/** Result of query `UpdateInvitationRsvp`. */
export interface IUpdateInvitationRsvpResult {
    id: string | null;
}

/** Result of query `ClearInvitationCompanions`. */
export interface IClearInvitationCompanionsResult {
}

/** Result of query `CreateInvitationCompanion`. */
export interface ICreateInvitationCompanionResult {
}

export interface Queries {
    FindOwner: IFindOwnerResult;
    ListInvitationGuests: IListInvitationGuestsResult;
    InvitationGuestById: IInvitationGuestByIdResult;
    InvitationGuestByToken: IInvitationGuestByTokenResult;
    CreateInvitationGuest: ICreateInvitationGuestResult;
    RevokeChangedInvitationMode: IRevokeChangedInvitationModeResult;
    UpdateInvitationGuest: IUpdateInvitationGuestResult;
    InvitationStats: IInvitationStatsResult;
    InvitationGroups: IInvitationGroupsResult;
    SetInvitationAccess: ISetInvitationAccessResult;
    RevokeInvitationAccessSessions: IRevokeInvitationAccessSessionsResult;
    RotateInvitationLink: IRotateInvitationLinkResult;
    RevokeRotatedInvitationSessions: IRevokeRotatedInvitationSessionsResult;
    RevokeInvitationSessions: IRevokeInvitationSessionsResult;
    AddInvitationReference: IAddInvitationReferenceResult;
    InvitationReferenceObservations: IInvitationReferenceObservationsResult;
    InvitationReferenceImage: IInvitationReferenceImageResult;
    RemoveInvitationReference: IRemoveInvitationReferenceResult;
    CreateInvitationSession: ICreateInvitationSessionResult;
    FindInvitationSession: IFindInvitationSessionResult;
    UpdateInvitationRsvp: IUpdateInvitationRsvpResult;
    ClearInvitationCompanions: IClearInvitationCompanionsResult;
    CreateInvitationCompanion: ICreateInvitationCompanionResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
