// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `ListNotes`. */
export interface IListNotesResult {
    id: string;
    body: string;
    createdAt: string;
}

/** Result of query `CreateNote`. */
export interface ICreateNoteResult {
}

/** Result of query `RemoveNote`. */
export interface IRemoveNoteResult {
    id: string;
}

export interface Queries {
    ListNotes: IListNotesResult;
    CreateNote: ICreateNoteResult;
    RemoveNote: IRemoveNoteResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
